clc; clear;
figure('Renderer', 'painters', 'Position', [0 0 1600 600]);
x = categorical({'elephant',	'lionFemale',	'lionMale',	'warthog',	'gazelleThomsons', ...	
    'wildebeest',	'gazelleGrants',	'zebra',	'hartebeest',	'giraffe',	'buffalo',	...
    'guineaFowl',	'otherBird',	'hyenaSpotted',	'ostrich',	'topi',	'eland',	'human', ...
    'impala',	'reedbuck',	'cheetah',	'dikDik',	'baboon',	'koriBustard',	'jackal', ...
    'secretaryBird',	'serval',	'mongoose',	'hare',	'batEaredFox',	'aardvark',	'porcupine', ...
    'hyenaStriped',	'leopard',	'aardwolf',	'waterbuck',	'vervetMonkey',	'hippopotamus',	'bushbuck', ...
    'caracal',	'wildcat',	'rodents',	'honeyBadger',	'civet',	'genet',	'rhinoceros', ...	
    'reptiles',	'zorilla'});
x = reordercats(x, {'elephant',	'lionFemale',	'lionMale',	'warthog',	'gazelleThomsons',	...
    'wildebeest',	'gazelleGrants',	'zebra',	'hartebeest',	'giraffe',	'buffalo',	...
    'guineaFowl',	'otherBird',	'hyenaSpotted',	'ostrich',	'topi',	'eland',	'human', ...
    'impala',	'reedbuck',	'cheetah',	'dikDik',	'baboon',	'koriBustard',	'jackal',	...
    'secretaryBird',	'serval',	'mongoose',	'hare',	'batEaredFox',	'aardvark',	'porcupine', ...
    'hyenaStriped',	'leopard',	'aardwolf',	'waterbuck',	'vervetMonkey',	'hippopotamus',	'bushbuck', ...
    'caracal',	'wildcat',	'rodents',	'honeyBadger',	'civet',	'genet',	'rhinoceros', ...
    'reptiles',	'zorilla'});
y = [7236,	5808,	1723,	1411,	1370,	1346,	1270,	1259,	1201,	1180, ...
    1066,	1041,	1016,	1000,	676,	674,	665,	629,	622,	570, ...
    569,	522,	498,	486,	468,	399,	373,	338,	331,	323, ...	
    280,	218,	208,	191,	183,	169,	144,	141,	90,	88,	86,	69, ...
    68,	57,	48,	45,	43,	26];
bar(x, y, 0.5);
ax = gca;
ax.FontSize = 14; 
xlabel('Animals', 'fontsize',14);
ylabel('Number of images', 'fontsize',14);
xtickangle(90);
ylim([0, 8000]);
grid on;
title('Training data distribution');
% h=text(1:length(y),y,num2str(y'));
% set(h, 'FontSize', 14);
% set(h,'Rotation',90);